name: Development Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  scan:
    name: Lint and SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm i --no-fund --no-audit
        working-directory: ./frontend

      - name: Apply linter
        run: npm run lint-fix
        working-directory: ./frontend
