name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Lint, SAST Scan, Build, Deploy and DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm i --no-fund --no-audit
        working-directory: ./frontend

      - name: Apply linter
        run: npm run lint-fix
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend
