name: main

on:
  push:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      #- uses: actions/setup-node@v4.1.0
      - run: npm i 
      - name: Lint
        run: cd ./frontend && npm run lint-fix
      - name: Build
        run: npm run build
