name: Portfolio CI

on:
  push:
    branches: ["main"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: cd ./frontend && npm i --no-fund --no-audit
      - name: Lint
        run: cd ./frontend && npm run lint-fix
      - name: Build
        run: cd ./frontend && npm run build
