name: Main workflow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Initialize SAST scan
        uses: github/codeql-action/init@v4.37.3
        with:
          languages: javascript-typescript

      - name: Run SAST analysis
        uses: github/codeql-action/analyze@v4.37.3

  dast:
    name: DAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Wait for preview deployment
        id: vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 180
          check_interval: 5
          vercel_protection_bypass_header: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: Run DAST analysis
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: ${{ steps.vercel.outputs.url }}
          fail_action: false
          allow_issue_writing: false
          cmd_options: '-a'
          artifact_name: dast-report
        env:
          ZAP_AUTH_HEADER: x-vercel-protection-bypass
          ZAP_AUTH_HEADER_VALUE: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
